# Generated by Django 6.0.4 on 2026-05-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_cardreview_deck_reviewlog_shelf_tag_deckcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_goal',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='scheduled_days',
            field=models.IntegerField(default=0),
        ),
    ]
