# Generated by Django 6.0.4 on 2026-05-06 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scratchnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardreview',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
