# Generated by Django 6.0.4 on 2026-05-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cardreview_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardreview',
            name='step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
